version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
    - 3306:3306
    expose:
    - 3306
    volumes:
    - /opt/mysql_data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=test_bank
  test_bank_api:
    image: test-bank-api:0.1.0
    container_name: test-bank-api
    depends_on:
    - mysql
    ports:
    - 8080:8080
    expose:
    - 8080
    environment:
    - DATABASE_HOST=mysql
    - DATABASE_NAME=test_bank
    - DATABASE_USER=root
    - MYSQL_ROOT_PASSWORD=admin
    - DATABASE_PORT=3306
    links:
    - mysql