spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    username: ${DATABASE_USER}
    password: ${MYSQL_ROOT_PASSWORD}
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql

---
spring:
  profiles: prod
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://mysql:3306/test_bank
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql